// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"clean-architecture-go/application/usecase"
	"clean-architecture-go/infrastructure/persistent/firestore"
	"clean-architecture-go/infrastructure/waf/echo/handler"
	"clean-architecture-go/interface/controller"
	"clean-architecture-go/interface/presenter/json"
)

// Injectors from wire.go:

func InitializeTaskHandler() handler.ITaskHandler {
	iTaskRepository := firestore.NewTaskFirestoreRepository()
	iTaskPresenter := jsonp.NewTaskJsonPresenter()
	iTaskUseCase := usecase.NewTaskUseCase(iTaskRepository, iTaskPresenter)
	taskController := controller.NewTaskController(iTaskUseCase)
	iTaskHandler := handler.NewTaskHandler(taskController)
	return iTaskHandler
}
